# Nome da Aplicação
spring.application.name=PortfolioBackend

# --- CONFIGURAÇÃO DO POSTGRESQL ---
# Se não achar DB_URL no .env, usa o localhost padrão
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/portfolio_db}

# Se não achar DB_USERNAME, usa o 'postgres'
spring.datasource.username=${DB_USERNAME:postgres}

# IMPORTANTE: Coloque sua senha real aqui após o ":" para testar se o problema é o .env
spring.datasource.password=${DB_PASSWORD:CNK8003@}

# Se não achar JWT_SECRET, usa uma chave de segurança para não dar erro no boot
api.security.token.secret=${JWT_SECRET:sequencia_longa_e_aleatoria_que_eu_acabei_de_inventar_com_toda_a_criatividade_restante!Gustavo2003@}

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# IMPORTANTE: necessário para o Neon aceitar a conexão SSL
spring.datasource.hikari.data-source-properties.sslmode=require